title: ~jack/website
author: Jack Rayner
email: me@jrayner.net
description: >-
    Hosted on Github Pages and made with ğŸ³ï¸â€ğŸŒˆ
baseurl: ""
url: "https://jrayner.net"
github_username: jackrayner

# Build settings
theme: minima
plugins:
  - jekyll-feed